version: "3"

services:
  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: '$DB_USER'
      POSTGRES_DB: '$DB_NAME'
      POSTGRES_PASSWORD: '$DB_PASSWORD'
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data/pgdata
    ports:
      - '5431:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
